on: push
name: Continuous Integration
jobs:
  build:
    name: docker://cdssnc/seekret-github-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker://cdssnc/seekret-github-action
      uses: docker://cdssnc/seekret-github-action
